### ISSUE TITLE
Generate a valid signature

### ISSUE THREAD

**Issue by s951736** [3commas-io/3commas-official-api-docs#1]
Hello, sorry if this is not allowed to post here.
I'm trying to connect 3commas api, but keep getting "signature_invalid" message.
When I try to produce hmac sha256 signature, I can get the correct result use the same parameters in [docs example](https://github.com/3commas-io/3commas-official-api-docs/blob/master/rest-api.md#signed-endpoint-examples-for-post-publicapiver1accountsnew), but I can't get my own secret key to work.

Here is what I do:

```
headers = {
    'APIKEY': 'XXX'
}

params=b'/public/api/ver1/deals'
secret = b'YYY'
signature = hmac.new( secret , params, hashlib.sha256).hexdigest()
query = "signature={}".format(signature)


resp = requests.request('GET',
                        'https://3commas.io' + params + "?" + query,
                        headers=headers)

reqsjson = json.loads(resp.text)
print(json.dumps(reqsjson, indent=4, sort_keys=True))
```

The error I get:
```
{
    "error": "signature_invalid", 
    "error_description": "Provided signature is invalid"
}
```

Any help would be much appreciated.

**Comment by abdelraoof** [comment]
> `SIGNED` endpoints require an additional header, `Signature`, to be sent.
So, you need to send the signature in the `Signature` header, not in the query string.

**Comment by sadgb** [comment]
also you could het some api related support here https://t.me/ld4ka

**Comment by 3commas-io** [comment]
https://t.me/ld4ka is a good choice to get fast support
