### ISSUE TITLE
Response 200 but no json data

### ISSUE THREAD

**Issue by breton123** [3commas-io/3commas-official-api-docs#107]
I'm trying to create a new bot using requests and the 3Commas API. Whenever I try a POST request I always get a response 200 but no json data. I am testing by trying to update my blacklisted pairs. Can anyone see why I get no json data? I have the same problem when I try to use Py3CW. Here is my code:
```
import requests
import hashlib
import hmac
import json

url = "https://api.3commas.io/public"
action="/ver1/bots/update_pairs_black_listpairs='USDT_BTC'"
params = str.encode("/public/api"+action)
key=""
secret=b""

signature = hmac.new(secret, params, hashlib.sha256).hexdigest()

x = requests.post((url+action),headers={"APIKEY":key,"Signature":signature},data={"pairs":'USDT_BTC'})
print(x)
print(x.json)
```

**Comment by EfremovEvgeniy** [comment]
Thank you, already in progress. It'll be fixed soon.
