### ISSUE TITLE
Ignoring paper orders

### ISSUE THREAD

**Issue by bogdanteodoru** [3commas-io/3commas-official-api-docs#11]
Seems that for whatever reason 3commas are ignoring paper orders. 

"Hi, from the last 10 days 3c.exchange is ignoring totally all the paper orders, anybody else is having this issue ? Thanks."

https://github.com/bogdanteodoru/py3cw/issues/5

**Comment by MoroZvlg** [comment]
Answer in python library issue. Also, you can check out telegram chat
