### ISSUE TITLE
Delete API is not working for Smart Trades

### ISSUE THREAD

**Issue by selva-krishnan** [3commas-io/3commas-official-api-docs#119]
I am using the DELETE API for Smart Trades to Delete a Trade. But I am always getting an error saying DELETE is not a supported METHOD.

{
    "error": "invalid_request_method",
    "error_description": "Your request method is not supported by this endpoint. Please use one of [OPTIONS, GET, HEAD]."
}

**Comment by EfremovEvgeniy** [comment]
Hi, do you use ```DELETE /v2/smart_trades/{smart_trade_id}/trades/{id}``` ?

**Comment by selva-krishnan** [comment]
Yes, I used the DELETE operation.

**Comment by EfremovEvgeniy** [comment]
{id} is a id of trade wich you want to delete
