### ISSUE TITLE
In /ver1/deals it should be possible to fetch by only bot_id (without account_id and forced mode)

### ISSUE THREAD

**Issue by sgerodes** [3commas-io/3commas-official-api-docs#120]
Right now if If send a request with a bot_id, but without account_id, if I am in the wrong mode (paper, real), an empty list is returned. 

Adding account_id or a the correct forced mode solves the problem

If I fetch a specific bot_id the mode is implicitly unambiguously known. Though specifying  account_id or a forced mode is redundant.

I think specifying the bot_id should be enough to get the results

**Comment by EfremovEvgeniy** [comment]
Hi, already in progress. It'll be fixed soon.
