### ISSUE TITLE
api/ver1/grid_bots Not accepting "from" query parameter

### ISSUE THREAD

**Issue by avarney06** [3commas-io/3commas-official-api-docs#125]
GET request to api/ver1/grid_bots including a datetime string for the "from" parameter is returning an "unknown error".
`{ error: 'unknown_error',
  error_description: 'Unknown error occurred#NoMethodError' }`
GET request is signed. Query Parameters Used.
`from=2021-02-18T14%3A11%3A45.787Z&offset=0&limit=20`
Removing the "from" query parameter and the GET request is successful returning all deals.

**Comment by EfremovEvgeniy** [comment]
Hi, thank you. We'll fix it soon, already in progress.
