### ISSUE TITLE
bots: swapping pairs does not work anymore

### ISSUE THREAD

**Issue by cklm** [3commas-io/3commas-official-api-docs#126]
We saw in the last hours, that the api `PATCH /ver1/bots/{bot_id}/update` doesn't allow to change pairs anymore. This is error we got:
```
got http 400 for "https://api.3commas.io/public/api/ver1/bots/XXX/update": {"error":"record_invalid","error_description":"Invalid parameters","error_attributes":{"pairs":["is invalid"]}}
```
The error occurs for every pair-update, regardless of the bot or market. The issue started today (2022-01-20) at around 10:30 UTC and still persists.

**Comment by JSlowik** [comment]
I am seeing this issue as well.

**Comment by Chris-Kaye** [comment]
Hi, thank your for reporting this issue, it should be resolved now.

**Comment by cklm** [comment]
Thanks, can confirm that its works again.
