### ISSUE TITLE
GET /ver1/smart_trades does not work properly

### ISSUE THREAD

**Issue by FredMichel** [3commas-io/3commas-official-api-docs#13]
Hi Team,

It was working fine there are a couple of month but I noticed it does not work anymore especially when api is called with {scope: 'active'} parameter.
Any breaking change somewhere?

Thank you.

**Comment by MoroZvlg** [comment]
There were no changes

If you think that there is a bug on our side - we need more information. 
Method, Ids, explanation, etc
