### ISSUE TITLE
Error "take_profit[steps][0][price][type]":["is missing"]

### ISSUE THREAD

**Issue by hummerh2** [3commas-io/3commas-official-api-docs#132]
I am getting the error below when creating a new smart trade with take profits enabled. It works fine with take profits disabled.

`"{"error":"record_invalid","error_description":"Invalid parameters","error_attributes":{"take_profit[steps]":["is invalid"],"take_profit[steps][0][price][type]":["is missing"],"take_profit[steps][0][price][value],take_profit[steps][0][price][percent]":["are missing, exactly one parameter must be provided"]}}"
`
I have seen a couple tickets where it is recommended to post a JSON request body which i actually prefer. However when I post json body i get the error below. 

`"{"error":"signature_invalid","error_description":"Provided signature is invalid"}"`

Does anyone have an example of the correct way to generate the hash signature when posting JSON instead of url array params? I am using php hash_hmac sha256. 

Thanks!

**Comment by hummerh2** [comment]
Finally found a solution after searching Telegram for hours. Would save people a lot of time if could show examples in the official docs of how to create the signature when using a JSON post. 

Thank you Darth Ada for posting your solution. Adding it to this ticket since I have not seen the solution anywhere else. 

`
$signThis =  '/public/api/v2/smart_trades?' . json_encode(YOUR [] ARRAY OF SMART TRADE DATA ONLY - NO API KEY OR SECRET HERE);
$sign = hash_hmac('sha256', $signThis, THREE_COMMAS_SECRET_KEY);
$finalApiURL = 'https://api.3commas.io' + $signThis;

$headers = array(
    'Content-Type: application/json',
    'Signature:' . $sign,
    'APIKEY:' . THREE_COMMAS_API_KEY
  );
curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($data));
curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'POST');
`

**Comment by omarhamdyHmach** [comment]
> 
$finalApiURL = 'https://api.3commas.io' + $signThis; 
to 
$finalApiURL = 'https://api.3commas.io' + $signThis without json
