### ISSUE TITLE
Validate ApiKey / ApiSecret endpoint

### ISSUE THREAD

**Issue by enterprisebug** [3commas-io/3commas-official-api-docs#137]
I like to check if my ApiKey / ApiSecret is valid.

Currently you have a `GET /ver1/ping` endpoint with `Permission: NONE Security; NONE`

It would be helpful to have a `GET /ver1/validate` endpoint with `Permission: NONE Security SIGNED`

**Comment by EfremovEvgeniy** [comment]
Hi, how you can use `GET /ver1/validate`
