### ISSUE TITLE
Average for smart trade v2 does not work properly

### ISSUE THREAD

**Issue by FredMichel** [3commas-io/3commas-official-api-docs#14]
When I send following payload : 

{
id : 123456,
order_type: "market",
units: { value: 30}
}

It returns following error 

 { error: 'record_invalid',
  error_description: 'Invalid parameters',
  error_attributes:
   { units: [ 'is invalid' ],
     'units[value]': [ 'is missing', 'is invalid' ] } }

Thank you for your assistance.

**Comment by MoroZvlg** [comment]
Is it ST update method? Is it a full payload?
The payload looks a little bit strange. I don't see "position" key.

**Comment by FredMichel** [comment]
Is is not the full payload but error message is strange even if I add the position key : 
 error: 'record_invalid',
  error_description: 'Invalid parameters',
  error_attributes:
   { position: [ 'is invalid' ],
     'position[units]': [ 'is missing', 'is invalid' ],
     'position[units][value]': [ 'is missing' ]
}

**Comment by MoroZvlg** [comment]
The data that you are providing is not enough to help you.
Please send full request payload with headers, body, parameters
