### ISSUE TITLE
what's the default value for "only_for_enabled" in open new deal?

### ISSUE THREAD

**Issue by marianolatorre** [3commas-io/3commas-official-api-docs#145]
by omission of only_for_enabled would that switch the bot back on  if called when the bot is off?

**Comment by Chris-Kaye** [comment]
For anyone else wondering this, the default value is False .

This means that any new signal received will start the bot and a new deal (assuming you don't already have an active deal running on a Single-pair Bot, or for a Multi-bot that the active trades running are less than the max_active_deals setting). 

If this value is set to "only_for_enabled" is set to True, then this means if your bot is disabled when a new signal is triggered, you'll get error code 422 back and no new deal will start.
