### ISSUE TITLE
Critical: “Forced-Mode”: “paper” request header is being ignored

### ISSUE THREAD

**Issue by AlgoDev1** [3commas-io/3commas-official-api-docs#146]
Hello,

I have some scripts integrating the 3Commas API and I am finding that as of this moment the Forced-Mode header (i.e. `"Forced-Mode": "paper"`, in order to create a paper account Smart Trade vs. a real account Smart Trade) is being ignored.

I think this is probably a pretty a critical error for users as I imagine a lot (like myself) make paper trades in development and don't assume the orders will get pushed to live exchanges.

Example (**this example works but creates a real trade right now because the "Forced-Mode" header is being ignored**)

```
curl -X POST -H 'APIKEY: <API key>' -H 'Accept: */*' -H 'Content-Type: application/json' -H 'Forced-Mode: paper' -H 'Signature: <the signature>' -d '{"account_id": <account id>, "leverage": {"enabled": false}, "pair": "USDT_BTC", "position": {"type": "buy", "order_type": "limit", "units": {"value": "0.1"}, "price": {"value": "21500.00"}}, "stop_loss": {"enabled": false}, "take_profit": {"enabled": true, "steps": [{"order_type": "market", "volume": 50.0, "price": {"type": "last", "value": "22000"}}, {"order_type": "market", "volume": 50.0, "price": {"type": "last", "value": "22100"}, "trailing": {"enabled": true, "percent": "1.00"}}]}}' https://api.3commas.io/public/api/v2/smart_trades
```

**Comment by EfremovEvgeniy** [comment]
Hi, we can not create 'paper' Smart Trade for real account. If you send real account id, real smart trade will be created for this account.
