### ISSUE TITLE
method GET /ver1/accounts/currency_rates dos not return 'lotStep'

### ISSUE THREAD

**Issue by cj4c0b1** [3commas-io/3commas-official-api-docs#15]
HI there at 3commas team.

Some times there is no 'lotStep' in the response.

Normal behavior :

> {'last': '0.00000087', 'bid': '0.00000086', 'ask': '0.00000087', 'orderbook_ask': '0.00000087', 'orderbook_bid': '0.00000086', 'orderbook_last': '0.00000087', 'orderbook_price_currency': 'BTC', 'strategy_name': 'orderbook_price', 'contract_strategy_name': 'orderbook_price', 'minPrice': '0.00000001', 'maxPrice': '1000.0', 'priceStep': '0.00000001', 'minLotSize': '1.0', 'maxLotSize': '90000000.0', 'lotStep': '1.0', 'minTotal': '0.0001'}

sometimes no 'lotStep' : maysbe is something missing for some markets.

> {'last': 8.6e-07, 'bid': 8.6e-07, 'ask': 8.7e-07, 'orderbook_ask': 8.7e-07, 'orderbook_bid': 8.6e-07, 'orderbook_last': 8.6e-07, 'orderbook_price_currency': 'BTC', 'strategy_name': 'orderbook_price', 'contract_strategy_name': 'orderbook_price', 'minLotSize': '454.54545455', 'minTotal': '0.0005', 'priceStep': '0.00000001'}

**Comment by MoroZvlg** [comment]
Hi. Can you send example with exchange and pair?

**Comment by cj4c0b1** [comment]
Hi guys
getting this error on this endpoint, same case.
It happening on FTX , I can reproduce the error on this  GRT/USD and USD_GRT at FTX.
The weird part is that it is intermittent. does not happen the same all the time.
In fact I'm confirming with this particular user and the problem happens with almost all USD pairs on FTX.
error :
`error getting pair information : {'error': 'Unknown pair'}`
this behavior was reported by @JoseCarlosDaSilva
