### ISSUE TITLE
Web version robot use problem, is it a bug?

### ISSUE THREAD

**Issue by freemanercom** [3commas-io/3commas-official-api-docs#150]
When the strategy is shorting, Quote is USDT, BaseCoin is BTC, there is no problem in the long-selling robot, but in the shorting robot transaction, the balance of the Assistant on the right shows 0.00000000BTC, there is only one shorting robot, there is no locked amount, but the short-selling The order fails, indicating that the btc balance is insufficient and is 0. But I have a balance of 100USDT in my account, and the balance cannot be 0 when converted into Bitcoin. But this is not the case in fake accounts. Is this a bug?

**Comment by Chris-Kaye** [comment]
If you are shorting on a Spot exchange account, then this is achieved by Selling coins you already hold and then Buying them back at a lower price, the "profit" made is actually the equity you release from the asset, as opposed to holding it as the asset's value falls.

Using the "short" strategy on spot is not the same as when trading futures contracts.
