### ISSUE TITLE
Some parameters causes `signature_invalid`

### ISSUE THREAD

**Issue by ozum** [3commas-io/3commas-official-api-docs#153]
When I made a GET request to `https://api.3commas.io/public/api/ver1/bots` some parameters causes `signature_invalid` error.

For example
OK: `https://api.3commas.io/public/api/ver1/bots?sort_by=created_at&strategy=short`
ERROR: `https://api.3commas.io/public/api/ver1/bots?sort_by=created_at&strategy=short&limit=10`

`limit`, `offset`, `scope`, `account_id` cause error.
However, `sort_by` and `strategy` are OK.

**Comment by Chris-Kaye** [comment]
Hi,
Please create a new signature for each unique request that you send and it should solve your issue.

**Comment by ozum** [comment]
Thanks, solved. The problem was related to the difference between the "POST" and"GET" parameters.
