### ISSUE TITLE
TP percentage condition available only with TrailingBuy

### ISSUE THREAD

**Issue by habeebmatrix** [3commas-io/3commas-official-api-docs#17]
When I place a SmartTrade Create, with TrailingBuyEnabled=false, and with TakeProfit and Stoploss enabled, it throws error:

{"error":"Wrong param(s)","error_description":"TP percentage condition available only with TrailingBuy"}

Isn't it possible to create a Smart Trade without TrailingBuy, and if I want TakeProfit and Stoploss?

**Comment by MoroZvlg** [comment]
First of all. Please, switch to STv2. STv1 is deprecated.

You should provide percentage values only for ST with conditional buy order with trailing. In any other case, it's not possible to set percentage values (you can calculate the exact price on your side)
