### ISSUE TITLE
Audio/btc binance grid bot errors

### ISSUE THREAD

**Issue by toaley** [3commas-io/3commas-official-api-docs#18]
Dear user,Thanks for your reply.With regard to your problem, the minimum order size of the trading pair Audio/BTC is 1, which means the minimum buy/sell order is 1 Audio, please kindly set the quantity is 1 or more than 1 and try again.​If the problem persists, please provide us the order details so that we can help you better.Thanks again for your waiting and understanding, if you have any questions in the future, please do come back to us, we will try our best to help you.At last, we hope you have a good journey in Binance. Best Regards, Binance Support Team | Dear user,Thanks for your reply.With regard to your problem, the minimum order size of the trading pair Audio/BTC is 1, which means the minimum buy/sell order is 1 Audio, please kindly set the quantity is 1 or more than 1 and try again.​If the problem persists, please provide us the order details so that we can help you better.Thanks again for your waiting and understanding, if you have any questions in the future, please do come back to us, we will try our best to help you.At last, we hope you have a good journey in Binance. Best Regards, Binance Support Team
![Screenshot_20201028-121518](https://user-images.githubusercontent.com/73569790/97384903-c6d07780-1924-11eb-80a3-469180fcf05f.png)

**Comment by MoroZvlg** [comment]
Do you have any questions?

**Comment by toaley** [comment]
I think this particular instance has been resolved thankyou
