### ISSUE TITLE
convert dust endpoint

### ISSUE THREAD

**Issue by cj4c0b1** [3commas-io/3commas-official-api-docs#21]
Hi there at 3commas

Will be very practical to have the endpoint to convert dust to BNB for binance and of course for 3c.exchange, as it already exist as an enpoint ion the Binance API.

https://binance-docs.github.io/apidocs/spot/en/#dust-transfer-user_data

**Comment by MoroZvlg** [comment]
Hi
I will add it to the feature request list.

**Comment by cj4c0b1** [comment]
thanks @MoroZvlg !

**Comment by 3commas-io** [comment]
it's on top of our backlog now

**Comment by cj4c0b1** [comment]
Hej guys, thanks by the update and adding this endpoint.

is there any tips to get it running ?

I'm receiving this response using the same api I used for trading, etc.

`{'error': 'access_denied', 'error_description': "Api key doesn't have enough permissions"}`

I doble checked the API and didn't find anything that should be suitable for change.

![image](https://user-images.githubusercontent.com/22513754/118356325-06834780-b575-11eb-80b7-3165790a8942.png)

I will do some tests and create a new API.

**Comment by cj4c0b1** [comment]
I assume that this endpoint is the same used when you click on 3commas interface
![image](https://user-images.githubusercontent.com/22513754/118392910-5416b780-b63c-11eb-9319-ba29a1b5a9fa.png)
and using the same api, but calling the endpoint complain about the {'error': 'access_denied', 'error_description': "Api key doesn't have enough permissions"}

**Comment by cj4c0b1** [comment]
thank you all.
this can now be closed it was covered by the [commit ebe68089589a1f6476f6636b85300dea093f3718](https://github.com/3commas-io/3commas-official-api-docs/commit/ebe68089589a1f6476f6636b85300dea093f3718)
