### ISSUE TITLE
account_table_data on_orders update timeframe

### ISSUE THREAD

**Issue by cj4c0b1** [3commas-io/3commas-official-api-docs#25]
Hej guys
I'm using this endpoint to watch for leftovers that remains for some reason without any orders attached, and after some time I noted that the field "on_orders" is not accurately updated.
I'm using it mostly on Binance and 3c.exchange.

Can you pls check on that or reply about the update timeframe for that respective field?

tkx.

**Comment by sadgb** [comment]
we pick this directly from Binance each time when they send a websocket message about it. Could you please provide some more details

**Comment by cj4c0b1** [comment]
lets close this one!
