### ISSUE TITLE
Grid bots list - [bug] inconsistent parameters

### ISSUE THREAD

**Issue by cj4c0b1** [3commas-io/3commas-official-api-docs#26]
Hi guys at 3commas team.
I just went to a bug on the grid bots list endpoint.

Name | Type | Mandatory | Values(default) | Description
-- | -- | -- | -- | --
account_ids | array[integer] | NO |   | Filter by account id
account_types | array[string] | NO |   | Filter by account type
state | string | NO | enabled, disabled | Filter by bot state
sort_by | string | NO | current_profit, bot_id, pair | Sort column
sort_direction | string | NO | desc, asc | Sort direction
limit | integer | NO | (10) |  
offset | integer | NO | (0)

check this out when you do not inform nothing in the payload you get only 10 bots.
if you inform the limit like 1000 without ANY other parameter, then you get all bots.
If you inform the limit and the account id, you get again only 10 bots.
can you pls check on that?

`payload = {}

len(bots)
10

payload = {'limit': 1000}

len(bots)
11

payload = {'limit': 1000, 'account_ids': 993456789}
len(bots)
10
`

tkx!

**Comment by 3commas-io** [comment]
WIP

**Comment by 3commas-io** [comment]
should work fine. Looks like you have 10 bots on that account. And since default limit is 10 too that could make some confusion
