### ISSUE TITLE
noob how-to for Google Sheets

### ISSUE THREAD

**Issue by eleaner** [3commas-io/3commas-official-api-docs#27]
Hi Guru's

Where could I find a more noob-friendly description of using this API to pull data to Google Sheets?
How can I sign the message?
In fact, I even fail to do it in Postman.

**Comment by 3commas-io** [comment]
You could ask this in our telegram community chat https://t.me/xcommas_api
because right now we dont have anything like this and i am not sure we will be able to allocate some resoures to develop smth like this
