### ISSUE TITLE
add parameters to get history for smartrades, grids, dca, or any endpoint with history

### ISSUE THREAD

**Issue by cj4c0b1** [3commas-io/3commas-official-api-docs#28]
Hello guys at 3commas team.
I'm working on a automated retrieval process for historic data from my bots and I just noted that all the endpoints to get historical data does not have a parameter to inform FROM date.
So, my request here is to add a parameter FROM Date or if you want to be compliant with the most APIs out there something like will be nice and certainly will save 3commas resources serving the API request.

Name | Type | Mandatory | Description
-- | -- | -- | --
startTime | LONG | NO | Default: 90 days from current timestamp
endTime | LONG | NO | Default: present timestamp
offest | INT | NO | default:0
limit | INT | NO |

**Comment by EfremovEvgeniy** [comment]
Hi, param 'from' added for bots, grid_bots, deals, smart_trades
