### ISSUE TITLE
SmartTrades - add status "partially_bought" or "partially_filled"

### ISSUE THREAD

**Issue by cj4c0b1** [3commas-io/3commas-official-api-docs#29]
Hi guys
This is an issue I'm tracking for a long time to confirm it is on the 3c side or my code.
And after a lot of observations i can confirm this :
1 opened smart trade with a limit order, status condition is buy_order_placed.
Then after some time without being bought it is canceled. then we get this:
![image](https://user-images.githubusercontent.com/22513754/102204113-b91d8400-3ec9-11eb-9b5d-96ce3842b7a3.png)
so, as you can see, all orders where CANCELED right ?
But NO!
The buy order was NOT canceled and the coin was bought in some time after this.
And you got THIS :
![image](https://user-images.githubusercontent.com/22513754/102204793-96d83600-3eca-11eb-847e-e9dc10b2ec4a.png)

this is happening all the time and i just observed the same issue with more then 10 smarttrades in the last 24 h.

My current solution was to create a bot that will check all open smartrades, dca and grid and pointme out what assets are "left"and not used in any orders.

I called it 3ca-audit-letfovers

![image](https://user-images.githubusercontent.com/22513754/102205281-47463a00-3ecb-11eb-8e3d-2df212a0d46a.png)

But the problem is that i need to manually deal with each of then, creating a manual smartrade, checking the bought price, etc,..

It seems that the problem is related to partial filled orders and there is no status for this on 3commas.

Can you pls add the status "partially_bought" or "partially_filled" for smartrades?

**Comment by cj4c0b1** [comment]
Interesting that just explaining the problem here i figured out a better way to solve my problem.
But the request is still valid.

**Comment by 3commas-io** [comment]
This issue also affects our web interface as well. Thanks

**Comment by cj4c0b1** [comment]
I think this can now be closed because I can sue this new status
[commit 8213bcc973fa0786cbcfd51fc4c62cb51f773490](https://github.com/3commas-io/3commas-official-api-docs/commit/8213bcc973fa0786cbcfd51fc4c62cb51f773490)
