### ISSUE TITLE
start_new_deal error with payload

### ISSUE THREAD

**Issue by riodda** [3commas-io/3commas-official-api-docs#30]
Hi, i'm testing the start new deal action:
if i send a plain start new deal command it works ok 
`#start deal
error, data  = p3cw.request(
    entity='bots', 
    action='start_new_deal',
    action_id='MYBOTID'    
)
data`

but if i want to specify the pair with the payload i have an error

`#start deal
error, data  = p3cw.request(
    entity='bots', 
    action='start_new_deal',
    action_id='2120923',
    #payload={'pair':['USDT_XMR'],'skip_signal_checks':'True','skip_open_deals_checks':'True'}
)
`
This is the error i have

`{'error': True,
 'msg': "Other error occurred: 'str' object has no attribute 'get'"}`

This is the bot as is configured:

`{'id': 2120923,
 'account_id': MYACCOUNTIR,
 'is_enabled': True,
 'max_safety_orders': 0,
 'active_safety_orders_count': 0,
 'pairs': ['USDT_XMR'],
 'strategy_list': [{'options': {}, 'strategy': 'manual'}],
 'max_active_deals': 1,
 'active_deals_count': 1,
 'deletable?': False,
 'created_at': '2020-12-16T16:15:56.210Z',
 'updated_at': '2020-12-16T16:32:39.367Z',
 'trailing_enabled': False,
 'tsl_enabled': False,
 'deal_start_delay_seconds': None,
 'stop_loss_timeout_enabled': False,
 'stop_loss_timeout_in_seconds': 0,
 'disable_after_deals_count': None,
 'deals_counter': None,
 'allowed_deals_on_same_pair': None,
 'easy_form_supported': False,
 'name': 'Test Bot',
 'take_profit': '5.0',
 'base_order_volume': '10.0',
 'safety_order_volume': '10.0',
 'safety_order_step_percentage': '1.0',
 'take_profit_type': 'total',
 'type': 'Bot::SingleBot',
 'martingale_volume_coefficient': '1.0',
 'martingale_step_coefficient': '1.0',
 'stop_loss_percentage': '0.0',
 'cooldown': '0',
 'strategy': 'long',
 'min_volume_btc_24h': '0.0',
 'profit_currency': 'quote_currency',
 'min_price': None,
 'max_price': None,
 'stop_loss_type': 'stop_loss',
 'safety_order_volume_type': 'quote_currency',
 'base_order_volume_type': 'quote_currency',
 'account_name': 'Paper Account 210260',
 'trailing_deviation': '0.2',
 'finished_deals_profit_usd': '0',
 'finished_deals_count': '0',
 'leverage_type': 'not_specified',
 'leverage_custom_value': None,
 'start_order_type': 'limit',
 'active_deals': [{'id': 236744748,
   'type': 'Deal',
   'bot_id': 2120923,
   'max_safety_orders': 0,
   'deal_has_error': False,
   'from_currency_id': 0,
   'to_currency_id': 0,
   'account_id': 29062281,
   'active_safety_orders_count': 0,
   'created_at': '2020-12-16T16:34:16.914Z',
   'updated_at': '2020-12-16T16:34:17.336Z',
   'closed_at': None,
   'finished?': False,
   'current_active_safety_orders_count': 0,
   'current_active_safety_orders': 0,
   'completed_safety_orders_count': 0,
   'completed_manual_safety_orders_count': 0,
   'cancellable?': True,
   'panic_sellable?': True,
   'trailing_enabled': False,
   'tsl_enabled': False,
   'stop_loss_timeout_enabled': False,
   'stop_loss_timeout_in_seconds': 0,
   'active_manual_safety_orders': 0,
   'pair': 'USDT_XMR',
   'status': 'bought',
   'take_profit': '5.0',
   'base_order_volume': '10.0',
   'safety_order_volume': '10.0',
   'safety_order_step_percentage': '1.0',
   'bought_amount': '0.06554',
   'bought_volume': '10.1111258248',
   'bought_average_price': '154.27412',
   'sold_amount': '0.0',
   'sold_volume': '0.0',
   'sold_average_price': '0',
   'take_profit_type': 'total',
   'final_profit': '-0.02347577',
   'martingale_coefficient': '1.0',
   'martingale_volume_coefficient': '1.0',
   'martingale_step_coefficient': '1.0',
   'stop_loss_percentage': '0.0',
   'error_message': None,
   'profit_currency': 'quote_currency',
   'stop_loss_type': 'stop_loss',
   'safety_order_volume_type': 'quote_currency',
   'base_order_volume_type': 'quote_currency',
   'from_currency': 'USDT',
   'to_currency': 'XMR',
   'current_price': '154.09',
   'take_profit_price': '162.15',
   'stop_loss_price': None,
   'final_profit_percentage': '0',
   'actual_profit_percentage': '-0.12',
   'bot_name': 'Test Bot',
   'account_name': '',
   'usd_final_profit': '-0.02',
   'actual_profit': '-0.0221662834',
   'actual_usd_profit': '-0.0221662834',
   'failed_message': None,
   'reserved_base_coin': '10.1111258248',
   'reserved_second_coin': '0.06554',
   'trailing_deviation': '0.2',
   'trailing_max_price': None,
   'tsl_max_price': None,
   'strategy': 'long'}]}`

**Comment by bhj2001** [comment]
How did you solve this?

**Comment by riodda** [comment]
There have been un update on the python wrapper i was using, now it's workig.
