### ISSUE TITLE
quantity_per_grid not taking values in decimal

### ISSUE THREAD

**Issue by upw-bhj** [3commas-io/3commas-official-api-docs#32]
If the value of 'quantity_per_grid' in https://github.com/3commas-io/3commas-official-api-docs/blob/master/grid_bots_api.md#create-grid-bot-permission-bots_write-security-signed is a decimal the following error comes

`{'error': True, 'msg': "Other error occurred: 'str' object has no attribute 'get'"}`

But, if it's value is rounded to an integer and sent then no error comes, it works perfectly fine.

The entire payload -

`{'account_id': xxxxx, 'pair': 'USDT_XLM', 'upper_price': 1.864588075, 'lower_price': 1.118752845, 'quantity_per_grid': 6.637518383, 'grids_quantity': 100.0, 'leverage_type': 'custom', 'leverage_custom_value': 20.0, 'is_enabled': False}`

**Comment by 3commas-io** [comment]
will work on it

**Comment by 3commas-io** [comment]
Nothing to do on our side, tested our api created multiple grids with decimal value in grid quantity
I also couldnt see this error in our logs so looks like this is smth in your code

**Comment by 3commas-io** [comment]
probably you are calling get method on str field ( because decimal is returned as a string )
