### ISSUE TITLE
Error units_to_buy: Should change with step 0.01

### ISSUE THREAD

**Issue by spiritix** [3commas-io/3commas-official-api-docs#34]
Getting the following error when doing an API call to `/ver1/smart_trades/create_smart_trade` when having `units_to_buy` set to a float with a precision > 2:

`{"error":"record_invalid","error_description":"Invalid parameters","error_attributes":{"units_to_buy":["Should change with step 0.01"]}}`

Now, this doesn't really make sense, since with the current BTC price 0.01 BTC would be $300, which is way higher than the minimum trade of $10.
Like this it's impossible to trade low amounts of high valued coins.

**Comment by 3commas-io** [comment]
smarttrades v1 is deprecated, please use  https://github.com/3commas-io/3commas-official-api-docs/blob/master/smart_trades_v2_api.md
