### ISSUE TITLE
deals/{deal_id}/show returns empty account_name

### ISSUE THREAD

**Issue by MarcDrexler** [3commas-io/3commas-official-api-docs#35]
The field "account_name" is always empty.
I know I can get the account name using the deal's account id by another method, but I think this needs to be fixed.

Endpoint: **/ver1/deals/{deal_id}/show**

Postman result:
<img width="287" alt="2021-02-12 12_17_16-Postman" src="https://user-images.githubusercontent.com/16029585/107761929-77278780-6d2c-11eb-93ae-ebfb69a02081.png">

**Comment by sadgb** [comment]
this field is deprecated and shouldnt be used

**Comment by 3commas-io** [comment]
deprecated
