### ISSUE TITLE
deals/add_funds not adding the right currency

### ISSUE THREAD

**Issue by imorandin** [3commas-io/3commas-official-api-docs#36]
When executing this in a BTC/USDT pair bot:

`deals/$deal_id/add_funds?deal_id=$deal_id&quantity=20&is_market=true`

It returns:

`{"error_description":"Insufficient funds","error":"not_enough_money"}`

But in the Bot log I see that it tried to buy BTC instead of USDT:

![image](https://user-images.githubusercontent.com/4126381/108582171-332a1900-7310-11eb-8871-e1cef6d56cde.png)

In the deals data (GET /ver1/deals/{deal_id}/data_for_adding_funds) it says that the "adding_funds_currency" is USDT:

`{"orderbook_price":"56711.15","price_per_one_unit_strategy_name":"orderbook_price","account_id":29199035,"quote_currency":"USDT","base_currency":"BTC","adding_funds_currency":"USDT","available_amount":"14649.61200751","limits":{"minPrice":"0.01","maxPrice":"200166.15","priceStep":"0.01","minLotSize":"0.000001","maxLotSize":"9000.0","lotStep":"0.000001","minTotal":"10.0","maxMarketBuyAmount":"100.10172496","maxMarketSellAmount":"100.10172496","marketBuyMinTotal":"10.0"},"market_supported":true,"is_contract":false,"take_profit_price":"200166.15","stop_loss_price":null,"account_type":"Account::PaperTradingAccount","deal_type":"long","pair":"USDT_BTC","limit":"10.00000000","market_buy_min_total":"10.0","min_lot_size":"0.00000100","leverage_custom_value":null}`

**Comment by EfremovEvgeniy** [comment]
Hi, I can't reproduce it. We need more recent cases to check logs.
