### ISSUE TITLE
/accounts Transfer History undocumented required parameter

### ISSUE THREAD

**Issue by AaronPowell96** [3commas-io/3commas-official-api-docs#37]
The parameters listed below are missing off a required parameter "size".
I have tried size Int and size string with "100", 100, but none work.
What is the size parameter?
Error:
  ```
"error_description": "{\"code\"=>-1102, \"msg\"=>\"Mandatory parameter 'size' was not sent, was empty/null, or malformed.\"}",
            "error": "unknown_market_api_error"
```
![image](https://user-images.githubusercontent.com/17838632/109015454-09c11280-76ad-11eb-9d01-dc138c88baaf.png)
![image](https://user-images.githubusercontent.com/17838632/109015591-2fe6b280-76ad-11eb-8eea-50e3efd442bb.png)

**Comment by 3commas-io** [comment]
Thanks for your request. An issue is now resolved
