### ISSUE TITLE
transfer_data not returning all accounts data

### ISSUE THREAD

**Issue by kirosc** [3commas-io/3commas-official-api-docs#38]
I added two exchange accounts but calling `transfer_data` only returning one exchange account.

**Comment by 3commas-io** [comment]
Please tell me your accounts types

**Comment by kirosc** [comment]
Not sure what you asking for. I linked more than one exchange account, but it only return accounts from one exchange.

I don't see any params in [transfer_data](https://github.com/3commas-io/3commas-official-api-docs/blob/master/accounts_api.md#data-for-transfer-between-accounts-permission-accounts_read-security-signed) to filter by `account_id`

```js
{
  available_currencies: [ 'USDT', 'BUSD', 'BNB' ],
  accounts: [
    {
      name: 'Binance Futures USDT-M',
      id: 1,
      code: 'binance_futures',
      balances: [Array]
    },
    {
      name: 'Binance',
      id: 2,
      code: 'binance',
      balances: [Array]
    }
  ]
}
```

**Comment by 3commas-io** [comment]
you could only transfer money to binance futures account and away from it. 
So transfer data should return only binance futures accounts

**Comment by kirosc** [comment]
> you could only transfer money to binance futures account and away from it. 
> So transfer data should return only binance futures accounts

I added several binance accounts so the retuned data length isn't correct.
