### ISSUE TITLE
SmartTrade Version2 Metadata Missing from 3commas_swaggerdoc.json

### ISSUE THREAD

**Issue by capricciobob** [3commas-io/3commas-official-api-docs#40]
The data structure that is returned from GET /v2/smart_trades is quite different than v1.

Is there any way to get an updated swaggerdoc.json file with metadata? Thanks!

**Comment by 3commas-io** [comment]
We are very sorry but our autogen tool couldnt generate swagger for it. 
I hope that some day this issue will be closed https://github.com/ruby-grape/grape-swagger/issues/817
and we will be able to upgrade grape-swagger. Also if someone will be brave enough to make pull request that would be great
