### ISSUE TITLE
Required Balance on Existing Grid Bot

### ISSUE THREAD

**Issue by capricciobob** [3commas-io/3commas-official-api-docs#41]
I am trying to edit a grid bot and want to check the balances before I restart the bot. This error is always returned. With a running bot, or a stopped bot. This call only seems to work on a bot that has not been started.

{"error":"unprocessable_entity","error_description":"The bot cannot be started. The process of canceling previous orders is ongoing. Try later."}

https://github.com/3commas-io/3commas-official-api-docs/blob/master/grid_bots_api.md#get-required-balances-to-start-botpermission-bots_read-security-signed

**Comment by 3commas-io** [comment]
Hm... orders cancels asynchoniously... but that should take much time

could you please share some bot ids and give  time when this issue was encountered last time

**Comment by 3commas-io** [comment]
ALso f you need to check how much money your bot is using at the moment you could use 
GET /ver1/grid_bots/{id}

investment_base_currency and investment_quote_currency
