### ISSUE TITLE
Edit bot API single parameter patch

### ISSUE THREAD

**Issue by JeeZues** [3commas-io/3commas-official-api-docs#42]
Edit bot (Permission: BOTS_WRITE, Security: SIGNED)
PATCH /ver1/bots/{bot_id}/update

Hi,

I'm trying to update a single parameter in my bot (max_active_deals) based on when my balance changes but failing to do that.
Looks like I need to send all other parameters to patch a bot.

Is there a future plan to allow a single parameter bot patch or am I doing it wrong?

Thanks,
JZ

**Comment by EfremovEvgeniy** [comment]
Hi, you have to send all of the required params to update the bot

**Comment by raymi** [comment]
I feel this is more a feature request than a bug report, so maybe this can be reopened?

It would be really nice to update individual aspects of a bot (like the `max_active_deals`) without having to read and send back the full bot config which is error-prone. Also, this would be in line with e.g. how you can update a deal via `PATCH /ver1/deals/{deal_id}/update_deal`
