### ISSUE TITLE
extend accounts/currency_rates  with maxleverage value

### ISSUE THREAD

**Issue by Kimage81** [3commas-io/3commas-official-api-docs#43]
For margin/future accounts, it would be handy to have a value displaying the max leverage. 
According to https://www.binance.com/en/support/articles/360033162192 this is dependent on the pair. 
Some have max 25x, others 25x of 75x. BTC has max of 125x

**Comment by 3commas-io** [comment]
we've added this method for you 

curl -X GET --header 'Accept: application/json' --header 'Platform: android' --header 'Appver: 1.6' 'https://api.3commas.io/api/v2/accounts/currency_rates_with_leverage_data?market_code=binance_futures&pair=USDT_BTC'

documentation will be added soon
