### ISSUE TITLE
smarttrading V2 missing buy steps

### ISSUE THREAD

**Issue by Kimage81** [3commas-io/3commas-official-api-docs#44]
In smarttrading V1 refreshsmarttrade result returns buy_steps as array with internal id (to cancel).
In V2, only a node "position" is returned, but no list of buy_steps.
 
It could be a quick win to take over the buy_steps of V1 to V2. 
This way buy_steps can be cancelled in V2, which was possible in V1

**Comment by 3commas-io** [comment]
Hi. Now you could use @GET("v5/smart_trades/{id}/trades")
to get all the trades and  cancel them or fill at market price like in STV1

@DELETE("v5/smart_trades/{trade_id}/trades/{order_id}")

@POST("v5/smart_trades/{trade_id}/trades/{order_id}/close_by_market")
