### ISSUE TITLE
/ver1/users/change_mode change mode also in GUI on the website

### ISSUE THREAD

**Issue by duskline** [3commas-io/3commas-official-api-docs#45]
When I work on API and e.g. automatically downloading data, the mode gets switched in background. When I switch in GUI API gets also affected. Can you please get rid of this dependency? It is anoying and also dangerous when I quickly need to do some changes or deal operations and scripted API access switch me over to paper multiple times when I quickly need to close deal.

**Comment by EfremovEvgeniy** [comment]
Hi, it'll be resolved in https://github.com/3commas-io/3commas-official-api-docs/issues/47
