### ISSUE TITLE
New Feature Request: Yesterday's Profit

### ISSUE THREAD

**Issue by weblancernz** [3commas-io/3commas-official-api-docs#46]
Hi,

Would it be possible to add a 'yesterdays profit' to the bot API?

I notice this is missing from your app too, and it's a feature I use every day but have to go through the web interface.

Thanks!

**Comment by mMeijden** [comment]
Highly interested into this feature as well. 
Currently i'm using a custom python script that executes this for me but it's limited to the dca bots.

would be great if we can invoke an endpoint to retrieve the profit (maybe optional date from/to range) 
to make it customisable

**Comment by EfremovEvgeniy** [comment]
@weblancernz Hi, could you attach a screenshot from the web interface? I want to ensure that I understand you correctly

**Comment by meghanarora** [comment]
Also a current todays prfoit would be great to see the days progress

**Comment by balpal74** [comment]
Did this ever get resolved? I'm trying to pull daily profits into Google Sheets

**Comment by EfremovEvgeniy** [comment]
Hi, you can use `GET /ver1/bots/stats_by_date`
