### ISSUE TITLE
Switching to paper trading account in the UI also switches API over

### ISSUE THREAD

**Issue by raymi** [3commas-io/3commas-official-api-docs#47]
The accounts etc. returned by the API depend on whether you selected the paper trading account in the web UI or not.

This seems dangerous as a single click in the UI can make all your API calls to go to the wrong accounts resp. fail

There's also no good way to test the API on paper trading while having a real setup running at the same time.

**Comment by imorandin** [comment]
+1 for this! same problem here!

**Comment by sgerodes** [comment]
+1 here. If somebody is browsing the 3 commas website it could interfere with the automated api calls heavily. And vice versa.

**Comment by sgerodes** [comment]
It is also annoying that for read the information from the paper account, you need a WRITE permission to switch to the real account.
IMHO It should be possible to read both account without the need to create WRITE enabled APIs.

**Comment by duskline** [comment]
+1 same problem - I also reported issue #45 for the same issue :) it is super annoying and only proper solution is to pay two accounts to not interfere with each other which seems quite a overkill to me :)

**Comment by JFBauer** [comment]
+1 This is more than annoying but even quite dangerous, I have a script checking for open deals and place either a new deal or a manual safety order. But i need to retrieve the deals to be able to place manual safety orders. If someone doesn't realise this issue and their code depends on it they could be in for a suprise!

**Comment by gatolim** [comment]
+1 Same problem here. Even thou the doc clearly said you can pass the account_id when querying but it just didn't work. It will only returns result if your passed in account_id is the same one as selected from UI.

**Comment by EfremovEvgeniy** [comment]
@raymi @imorandin @sgerodes @gatolim @JFBauer 
Hi, you can set a forced mode for public API through the request header "Forced-Mode" with values "real" or "paper".
