### ISSUE TITLE
"msg": "Other error occurred: record_invalid Invalid parameters."

### ISSUE THREAD

**Issue by GetSun2EZ** [3commas-io/3commas-official-api-docs#48]
Hello guys, i have a problem.
I use the smart trade v2 with bogdanteodoru/py3cw application and I got this error this error many times in the row but sometimes the order passes and I dont change the type of each values.

Someone can help me plz ?

id_account = int
pair = str
unit_value = float
entry = float
levarage = str
all target = float
stop = float
I want buy a coin with a specific price. I have a other payload with a buy market but this one in most important. Thx a lot

            error, data = p3cw.request(
                entity='smart_trades_v2',
                action='new',
                payload={
                    "account_id": id_account,
                    "pair": pair,
                    "instant": "false",
                    "position": {
                        "type": "buy",
                        "units": {
                            "value": unit_value
                        },
                        "order_type": "conditional",
                        "conditional": {
                            "price": {
                                "value": entry
                            },
                            "order_type": "market"
                        }
                    },
                    "leverage": {
                        "enabled": True,
                        "type": "custom",
                        "value": leverage
                    },
                    "take_profit": {
                        "enabled": "true",
                        "steps": [
                            {
                                "order_type": "limit",
                                "price": {
                                    "value": targets[0],
                                    "type": "bid"
                                },
                                "volume": 25
                            },
                            {
                                "order_type": "limit",
                                "price": {
                                    "value": targets[1],
                                    "type": "bid"
                                },
                                "volume": 25
                            },
                            {
                                "order_type": "limit",
                                "price": {
                                    "value": targets[2],
                                    "type": "bid"
                                },
                                "volume": 25
                            },
                            {
                                "order_type": "limit",
                                "price": {
                                    "value": targets[3],
                                    "type": "bid"
                                },
                                "volume": 25
                            }
                        ]
                    },
                    "stop_loss": {
                        "enabled": "true",
                        "order_type": "market",
                        "conditional": {
                            "price": {
                                "value": stop,
                                "type": "bid"
                            }
                        }
                    }
                }
            )

**Comment by lathamfell** [comment]
"custom" leverage doesn't work, you have to put either "isolated" or "cross"
