### ISSUE TITLE
unknown_market50x_error

### ISSUE THREAD

**Issue by imorandin** [3commas-io/3commas-official-api-docs#49]
Hi,

Sometimes I get error:
{"error_description":"Network error occurred. HTTP code: 502","error":"unknown_market50x_error"}

When executin API query: /public/api/ver1/deals/437364155/data_for_adding_funds

What does it mean?

Thanks,

Ignacio

**Comment by EfremovEvgeniy** [comment]
Hi, it's just a network error from the exchange, you just need to try again
