### ISSUE TITLE
Swagger doc out of date

### ISSUE THREAD

**Issue by hexate** [3commas-io/3commas-official-api-docs#50]
The swagger doc is out of date (missing smart trade V2) so I don't know what to expect in the response.

**Comment by MarcDrexler** [comment]
Also, I just wasted some time only to find out that the swagger json was out of date :( I also need Smart Trade V2 in it.

Please update or remove. But a swagger doc out of date will only make a lot of people lose their time.

**Comment by mglasner** [comment]
Please update Smart Trade V2 Docs ..

**Comment by EfremovEvgeniy** [comment]
@hexate @MarcDrexler @mglasner 
Hi, the documentation has been updated
