### ISSUE TITLE
add active_deals_usd_profit field in /bots endpoint

### ISSUE THREAD

**Issue by sgerodes** [3commas-io/3commas-official-api-docs#51]
Currently the active_deals_usd_profit could be obtained from the /bots/stats endpoint. I think it is a good metric to add in the /bots response. It has almost all information anyway.
Right now, If I need to have that metric for all enabled bots, I would need to send a request for every single bot id to /bots/stats.

**Comment by EfremovEvgeniy** [comment]
Hi, field added
