### ISSUE TITLE
/bots/stats?bot_id=<id> should return null instead of 0

### ISSUE THREAD

**Issue by sgerodes** [3commas-io/3commas-official-api-docs#52]
In other case a misleading information is given. 
Account: real
GET /bots/stats?bot_id=<some_id> returns something like this

```
{
    "overall_stats": {
        "BTC": "0.05083003"
    },
    "today_stats": {
        "BTC": "0.00364445"
    },
    "profits_in_usd": {
        "overall_usd_profit": 2922.1,
        "today_usd_profit": 209.51,
        "active_deals_usd_profit": -1848.31
    }
}
```

When we switch to the paper account and perform the same GET this response is returned:
```
{
    "overall_stats": {},
    "today_stats": {},
    "profits_in_usd": {
        "overall_usd_profit": 0.0,
        "today_usd_profit": 0.0,
        "active_deals_usd_profit": 0.0
    }
}
```

This gives misleading information. overall_usd_profit is stated a zero, which is a valid value for this field and should be interpreted that the is no profit. This is clearly not true. 

A better approach would be to return null in that case. null is not equal to 0. 0 IS a value, null is absence of a value.
```
{
    "overall_stats": {},
    "today_stats": {},
    "profits_in_usd": {
        "overall_usd_profit": null,
        "today_usd_profit": null,
        "active_deals_usd_profit": null
    }
}
```

**Comment by 3commas-io** [comment]
The information you provided is true. 
null is better when we are talking about "nothing"

However this is not safe to change in a running program. When we will have next version of this endpoint we will add null.
