### ISSUE TITLE
Is it possible to get bot list name

### ISSUE THREAD

**Issue by zoom2009** [3commas-io/3commas-official-api-docs#54]
I have read document but it's limit only 100 records.
Is it possible to get all bot_name or bot_id.
thank you

![image](https://user-images.githubusercontent.com/33366155/117199842-e20cca00-ae14-11eb-880b-8828c72d0cb4.png)

**Comment by 3commas-io** [comment]
to achive that you could query bots in batches of 100. Page by page - check the offset parameter
