### ISSUE TITLE
Bot removal affects Daily Summary Overview 

### ISSUE THREAD

**Issue by mMeijden** [3commas-io/3commas-official-api-docs#55]
**Problem:**

Removal of bots affects the daily summary overview. 
I have a few bots i don't want to use anymore, but when i remove them it will reduce the total amount in the daily summary.
By retaining the bots i won't be able use the stop/start all commands.

**Proposed Solution:**
Can we introduce an option to archive the bots so it won't affect the daily summary or separate the daily summary graph from the bots statuses.

**Comment by 3commas-io** [comment]
our product i thinking about it now

**Comment by 3commas-io** [comment]
Sorry, but this is intended behavior
