### ISSUE TITLE
retrieve shared bot details

### ISSUE THREAD

**Issue by SteveL1** [3commas-io/3commas-official-api-docs#56]
I'm trying to make an API call to retrieve shared bot details.  The web url is in the format https://3commas.io/bots/xxxxx/shared_show?secret=xxxxxx.  

When I try to retrieve this using the /bots/show call i get a not_found error

Is there a way to pull back the bot details in code?

**Comment by EfremovEvgeniy** [comment]
Hi, you can use `GET /ver1/bots/{bot_id}/show` if your bot has not been deleted.

**Comment by psstefanov** [comment]
Yes, this is the solution:
`curl https://3commas.io/bots/{bot_id}/get_bot_data?secret={secret}`

In Python, you can get the element you need with"
```
r = requests.get('https://3commas.io/bots/{bot_id}/get_bot_data?secret={secret}')
shared_bot=r.json()
print(shared_bot['bot_info']['bot_pair_or_pairs'])
```
