### ISSUE TITLE
in public/api/ver1/bots  there should be a field that shows profit in the quote currecny

### ISSUE THREAD

**Issue by sgerodes** [3commas-io/3commas-official-api-docs#61]
I have a BTC bot. When I fetch the values from my bot the only value I am getting is the finished_deals_profit_usd that shows the profit in usd.

**Comment by 3commas-io** [comment]
which endpoint (url ) are you using ?

**Comment by sgerodes** [comment]
/ver1/bots/stats

**Comment by EfremovEvgeniy** [comment]
@sgerodes Hi
We have a response in this format
```
{
    overall_stats: , # quote profit
    today_stats: , # quote profit
    profits_in_usd: {
       overall_usd_profit: , # usd profit
       today_usd_profit: , # usd profit
       active_deals_usd_profit: , # usd profit
     }
 }
```
We can add ```active_deals_profit``` in QUOTE or this is not enough?
