### ISSUE TITLE
Can't get any deals in /deals/ endpoint for particular account_id

### ISSUE THREAD

**Issue by Amantel** [3commas-io/3commas-official-api-docs#64]
Can't find an existing deals in results of `/public/api/ver1/deals` endpoint. 
If I supply `account_id`, I get empty array
If I do not supply any info, I can't find any deals for that `account_id`

This is paper account.

**Comment by gatolim** [comment]
possibly related [#47 ](https://github.com/3commas-io/3commas-official-api-docs/issues/47)

**Comment by Amantel** [comment]
Tested and confirmed. Problem was in paper account.
