### ISSUE TITLE
After updating a deal the /ver1/deals/:deal_id/show  endpoint shows wrong data

### ISSUE THREAD

**Issue by sgerodes** [3commas-io/3commas-official-api-docs#67]
How to reproduce:
- Create a bot.
- Start a deal with the bot (the bot has SL 10)
- Update the deal directly through The UI https://3commas.io/deals on the website.
- GET /ver1/deals/:deal_id/show. 
- "stop_loss_percentage" is still "10.0". But on the website the deal appears as having SL 7.

**Comment by MoroZvlg** [comment]
I can't reproduce your issue. It returns 7 for me
Can you double check and provide more info, please.

**Comment by sgerodes** [comment]
Double checked. It is indeed correct. My fault, sorry. Maybe I used not the correct id. Closing
