### ISSUE TITLE
Add a remove_funds functionality for deals

### ISSUE THREAD

**Issue by sgerodes** [3commas-io/3commas-official-api-docs#68]
Contrary to add_funds there could be a remove_funds. This endpoint would be very useful because it could simulate partial TP.

**Comment by 3commas-io** [comment]
This one is blocked by "multiple TP for deals feature". Once it will be done we will prceed with this one

**Comment by rupebac** [comment]
what is the preferred workaround for this? I mean, how to exit partially a position?
