### ISSUE TITLE
The error responses for /ver1/deals/:deal_id/add_funds should be more informative

### ISSUE THREAD

**Issue by sgerodes** [3commas-io/3commas-official-api-docs#69]
By every error I receive a 500 http code and this message:
{
    "error_description": "Network error occurred. HTTP code: 503",
    "error": "unknown_market50x_error"
}
or this:
{
    "error": "unknown_error",
    "error_description": "Unknown error occurred#Exceptions::OrderCancellingNeedsToWaitForInfo"
}

It is not clear at all what the issue was.

**Comment by 3commas-io** [comment]
unknown_market50x_error means that either exchange throws 500 error or network error occured. It's better to refresh deal and try again. 

OrderCancellingNeedsToWaitForInfo means that we sent cancel request to exchange, however when we queried order status it was still active. So it's required to wait a bit untill exchange confirms order cancellation
