### ISSUE TITLE
Close dela at market price missing endpoint?

### ISSUE THREAD

**Issue by riodda** [3commas-io/3commas-official-api-docs#7]
HI, i haven't found the proper way to close a deal trough the API, from the tv signals i can invoke close_at_market_price. 
Can't find the equivalent in the deals API, only panic sell.

**Comment by MoroZvlg** [comment]
panic_sell = close_at_market_price. It's legacy in naming. So, panic_sell is what you need

**Comment by riodda** [comment]
Ok, thanks.

 

Da: AS <notifications@github.com> 
Inviato: martedì 16 giugno 2020 10:05
A: 3commas-io/3commas-official-api-docs <3commas-official-api-docs@noreply.github.com>
Cc: Dario <riodda@gmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [3commas-io/3commas-official-api-docs] Close dela at market price missing endpoint? (#7)

 

panic_sell = close_at_market_price. It's legacy in naming. So, panic_sell is what you need
