### ISSUE TITLE
Add rate limits info to the docs

### ISSUE THREAD

**Issue by Amantel** [3commas-io/3commas-official-api-docs#75]
Hi! 

Checking the docs I failed to find proper info about rate limits. 
In the telegram channel I managed to find the following: 
```
"1. Overall API Rate limit is 15 requests per 1 second per IP. We understand that sometimes you need to update batch of entries or panic sell batch of smart trades or deals so requests to panic_sell and update  has significally higher burst limit. Even 1000requests/second for 5 seconds in a row should be fine"
```

Can we add that to the docs?

**Comment by EfremovEvgeniy** [comment]
Hi, we have intelligent protection for our rate limits.  If you have a problem with it, you can write to our support team.
