### ISSUE TITLE
grids, error updating grids

### ISSUE THREAD

**Issue by cj4c0b1** [3commas-io/3commas-official-api-docs#77]
Hi there ate 3c Team.

Please update the API docs about the new requirement to update grids.
This is the error caused by not informing the new parameters :

`{
	'error': 'record_invalid',
	'error_description': 'Invalid parameters',
	'error_attributes': {
		'name': ['is too short (minimum is 1 character)', 'is too long (maximum is 40 characters)', "can't be blank"]
	}
}`

this error was reported today at 11:19 UTC.

Is there a new change coming about one of my requestes to be possible to give a name to a grid ?

Thank you!

**Comment by 3commas-io** [comment]
fix. Grid bots should support names now. we will add more detailed information in documentation later today
