### ISSUE TITLE
Creating a bot returns error for strategy list

### ISSUE THREAD

**Issue by AmmarKothari** [3commas-io/3commas-official-api-docs#8]
I cannot create a bot from the python wrapper.

I created this issue: https://github.com/bogdanteodoru/py3cw/issues/3
And a few days before, someone else created a similar issue: https://github.com/bogdanteodoru/py3cw/issues/1

The other two APIs do not have any posted issues for this problem.  

The issue is in how the strategy list is formatted.  I believe the problem is either the endpoint is structured differently than documented, or something special needs to be done for the formatting of the request that is different than how the requests package usually formats payloads.

Would it be possible to get an example request that successfully creates a bot to verify the endpoint?  I think I can work back from that to figure out how the payload should be formatted within the Python wrapper to create a bot.

**Comment by amigoni** [comment]
Having the same issue. I send back the same strategy I get with the botInfo call and it says strategy can't be empty.

**Comment by AmmarKothari** [comment]
bump

**Comment by MoroZvlg** [comment]
It should be the same issue https://github.com/rentorm/3commas-api-node/issues/2
And this problem is not on our side. In such cases, we receive an empty parameter( take_profit_steps=[] or strategy_list=[]).

**Comment by bogdanteodoru** [comment]
@amigoni @AmmarKothari so basically for those payloads you need to stringify them before actually sending them. My library doesn't do such a thing.

**Comment by AmmarKothari** [comment]
Ah that makes sense.  Is there an example of a correctly stringified request?

**Comment by bogdanteodoru** [comment]
@AmmarKothari from what I see this should do the trick. I haven't tried it yet.
`payload=json.dumps(data, separators=(',', ':'))`

**Comment by AmmarKothari** [comment]
No still didn't work 😭 .  But did get a new error message.

I tried a few different points to convert the data using the json.dumps command, but none worked.  Below is the payload format when using json_dumps on the values associated with the 'strategy_list' key.  I also tried it with just an empty list strategy list and got the same error.

```
Payload Dump:
 {'name': 'test', 'account_id': 105110, 'pairs': ['BTC_DATA'], 'max_active_deals': 1, 'base_order_volume': 0.1, 'base_order_volume_type': 'quote_currency', 'take_profit': 1.0, 'safety_order_volume': 0.1, 'safety_order_volume_type': 'quote_currency', 'martingale_volume_coefficient': 1.0, 'martingale_step_coefficient': 1.0, 'max_safety_orders': 1, 'active_safety_orders_count': 1, 'stop_loss_percentage': 0.0, 'cooldown': 0, 'trailing_enabled': False, 'trailing_deviation': 0.1, 'strategy': 'long', 'safety_order_step_percentage': 1.0, 'take_profit_type': 'total', 'strategy_list': '[{"strategy":"trading_view","options":{"time":"5m","type":"buy_or_strong_buy"}}]', 'leverage_type': 'not_specified', 'stop_loss_timeout_enabled': False, 'stop_loss_timeout_in_seconds': 0, 'min_volume_btc_24h': 0.0, 'tsl_enabled': False, 'profit_currency': 'quote_currency', 'start_order_type': 'limit', 'stop_loss_type': 'stop_loss', 'allowed_deals_on_same_pair': 1}
```

This was the response:
`{'error': 'not_found', 'error_description': 'Not Found'}`

**Comment by MoroZvlg** [comment]
@AmmarKothari check your account_id. There is no account with such ID.

**Comment by AmmarKothari** [comment]
@MoroZvlg thanks for finding that error.  It works with the stringify command.  I had to do the same thing to the pairs list.  Thanks for helping figure this out.  @bogdanteodoru that fixed work if you want to update the readme.  I am also happy to open a PR for adding a function to fix those fields to make it easier for future users.

**Comment by bogdanteodoru** [comment]
@AmmarKothari, yes, please do a PR. Thanks.
