### ISSUE TITLE
Deals API: reserved_base_funds property in DealEntity should always be string

### ISSUE THREAD

**Issue by stolzem** [3commas-io/3commas-official-api-docs#85]
reserved_base_funds property in DealEntity is usually a string, but if value is 0 the type changes to number:

Correct as string:

```
 {
        "id": 698181939,
        "type": "Deal",
...
        "reserved_quote_funds": "10.093596",
        "reserved_base_funds": "34.9"
    },
```

Incorrect as number:

```
    {
        "id": 697805436,
        "type": "Deal",
...
        "reserved_quote_funds": "26.6214787",
        "reserved_base_funds": 0
    }
```

It should not change type just because it is 0. JSON parsers tend to freak out due to this.
You might want to check other fields for this problem as well.

**Comment by EfremovEvgeniy** [comment]
Hi, fixed
