### ISSUE TITLE
grid_bots_api.md incorrect for call to grid_bots/{id}/profits

### ISSUE THREAD

**Issue by tcurtin** [3commas-io/3commas-official-api-docs#86]
Issue with API documentation on https://github.com/3commas-io/3commas-official-api-docs/blob/master/grid_bots_api.md -- says the call GET /ver1/grid_bots/{id}/profits will return 
```
Profit
{
period: string 
 amount: number 
 chart_data: array 
 }
```

but that's not true -- it actually returns a
```
GridBotProfitsEntity
{
grid_line_id: '8000'                      
profit: '0.01'                            
usd_profit: '100'                         
created_at: 2018-08-08 08:08:08           
}
```

**Comment by matteoterzi** [comment]
Having the same issue!

**Comment by tcurtin** [comment]
Also, see #87 for the fact that GridLineEntity doesn't include its grid_line_id, so that is a dependency for this to be useful.

**Comment by EfremovEvgeniy** [comment]
Hi, fixed

**Comment by tcurtin** [comment]
YES Thank you!!!!!  #87 next I hope?  👍

**Comment by EfremovEvgeniy** [comment]
Yep, in progress right now
