### ISSUE TITLE
GridLineEntity doesn't include grid_line_id

### ISSUE THREAD

**Issue by tcurtin** [3commas-io/3commas-official-api-docs#87]
### What price did a grid_bots/{id}/profits row happen at?  This bug prevents the user from knowing.

`GridLineEntity` doesn't include `grid_line_id` values, so there's no way to connect a `GridBotEntity.grid_line_id` to corresponding `GridLineEntity`.

This is important because `GridBotProfitsEntity` references `grid_line_id`, but there's no way to know what that means since GridLineEntity has no id included.

This would help developers plug the hole that there's no way to understand how any profit was actually calculated.

**Comment by tcurtin** [comment]
(Note that this is a dependency for the utilization of #86.)

**Comment by tcurtin** [comment]
Guys - its been **4 months** on this request to add relevant data you already have to a data structure you're already returning!  This is a low effort high reward bug.  Any timeline on making the change?

`ver1/grid_bots` return includes per bot:
```
#            'grid_lines' => [
#                              {
#                                'price' => '41709.0',
#                                'order_placed' => $VAR1->[0]{'is_enabled'},
#                                'side' => undef
#                              },
#								...
#                            ],
```

Notice that grid_lines data does **not** include each line's unique id.

Now call `ver1/grid_bots/$id/profits`:
```
          {
            'profit' => '1.11431207',
            'usd_profit' => '1.11431207',
            'grid_line_id' => 40419578,
            'created_at' => '2021-07-30T23:37:27.056Z'
          },
...
```

If that `grid_line_id` you return only matched something we could find elsewhere in data we already have (since we needed to get the bot list to get the id to pass to the profits call) we'd know **at what price the profit happened**.

**Comment by tcurtin** [comment]
And a happy new year!  I see this in `ver1/grid_bots` data now:
```
          'grid_lines' => [
                            {
                              'side' => undef,
                              'price' => '0.1702',
                              'order_placed' => bless( do{\(my $o = 0)}, 'JSON::PP::Boolean' ),
                              'id' => 58855661
                            },
```
That's an id I see!  THANK YOU!!!  Now I can finally connect profits to their associated prices.  To work I go.

**Comment by EfremovEvgeniy** [comment]
@tcurtin Hi, happy new year! Yep, we added id to GridLineEntity, add GridLineEntity description in docs, and return GridLineEntity in GridBotProfitsEntity
 {
grid_line_id: integer 
  profit: string 
  usd_profit: string 
  created_at: string 
  grid_line: GridLineEntity 
  }
