### ISSUE TITLE
no definition of `GridLineEntity` in docs grid_bots_api.md

### ISSUE THREAD

**Issue by tcurtin** [3commas-io/3commas-official-api-docs#88]
There's no definition of `GridLineEntity` in the docs at https://github.com/3commas-io/3commas-official-api-docs/blob/master/grid_bots_api.md.

(There is at https://github.com/3commas-io/3commas-official-api-docs/blob/b3195e890d4fbf9789ce96bd94fed82a27ad394a/3commas_swaggerdoc.json but it should be propagated to the human-readable version.)

**Comment by EfremovEvgeniy** [comment]
Hi, fixed
