### ISSUE TITLE
Consider adding 'note' parameter to SmartTradesV2 API?

### ISSUE THREAD

**Issue by mrobe** [3commas-io/3commas-official-api-docs#9]
SmartTradesV2 API looks good!

However, I don't see a **note** parameter for "Create smart trade". Apparently, there is now a separate "Set note" endpoint for this purpose.

It would be nice to have **note** as an optional parameter, because it can be used to hold a token that enables the client (e.g., a trading app) to identify the order on the exchange.

The scenario is this: (1) a HTTPS connection is opened and "Create smart trade" is POSTed to the server (2) HTTPS connection fails, returning a timeout error to the client. At this point, the order has been processed by the exchange, but the client _doesn't have confirmation_, and the "Set note" endpoint doesn't help. The client must now query for all open orders and try to guess a match. This would be easier if the client could provide a unique token via the **note** parameter.

Thanks!

**Comment by MoroZvlg** [comment]
Hi, thanks a lot for your report! 
I agree with you. It should be in create ST method.
We will add it to the feature requests list.

**Comment by sadgb** [comment]
We've added note to ST v2 

thanks for your feedback

**Comment by 3commas-io** [comment]
We've added note to ST v2

thanks for your feedback
