### ISSUE TITLE
Is there a sandbox available?

### ISSUE THREAD

**Issue by doingandlearning** [3commas-io/3commas-official-api-docs#95]
Hi,

I've a few ideas for how I'd like to interact with the API but I don't want to be triggering trades while testing. 

Is there a sandbox available to test the API before I start applying this to real trades?

Thanks.

**Comment by chriskaye** [comment]
Hi, 
When you are first creating code, you can try GET requests only until you feel confident to move up to creating Smart Trades and Bots; at this point, you can use the Paper Trading account in 3Commas and create many practice bots and trades here, without risking real funds.
