### ISSUE TITLE
Creating signature for /v2/smart_trades route with JSON body

### ISSUE THREAD

**Issue by doingandlearning** [3commas-io/3commas-official-api-docs#98]
Hi,

I'm POSTing to `/public/api/v2/smart_trades` with a JSON body. 

The documentation tells how to construct a signature for a signed route for a base route and a route with query parameters. I'm not clear on how to construct a signature for requests with a JSON body.

- I've tried using `/public/api/v2/smart_trades` as the string to encode
- I've tried using `/public/api/v2/smart_trades?` and then iterating over the key/value pairs adding `key=value` and ensuring there isn't an & at the end

Is there something I'm missing?

Thanks,
Kevin.

**Comment by walidbahgat** [comment]
could you tell us, how did you resolve the issue

**Comment by ericjeker** [comment]
Hey guys,

I just wanted to answer this as it took me a while to figure it out:

Basically, you have to concatenate the URI, with a question mark (?), and the BODY as a flat JSON string. I removed all the spaces and new line characters before generating the signature.

Created a Gist with my helper functions (in Javascript), hope it helps and let me know if I made a mistake:
https://gist.github.com/ericjeker/47185c9fe9127e9e2d2cefa033165d8e

The signature has to be stored in a "Signature" header.

If you use `axios`, don't pass the body as a string in the `data` property but pass the JSON object instead.

Cheers,
